### ISSUE TITLE
suggest disable tqdm

### ISSUE THREAD

**Issue by thangckt** [MDIL-SNU/SevenNet#117]
hi @YutackPark 

I suggest to remove `tqdm` during process of graph_build
In almost practices, we work on headless mode cluster, then have no chance to see status bar, but the redudant print like this:
```sh
graph_build (1):   0%|          | 0/10000 [00:00<?, ?it/s]
graph_build (1):   2%|▏         | 19/10000 [00:00<00:04, 187.66it/s]
graph_build (1):   6%|▌         | 45/10000 [00:00<00:03, 225.33it/s]

graph_build (1):  98%|█████████▊| 9999/10000 [00:02<00:00, 261.32it/s]
graph_build (1): 100%|██████████| 10000 /10000 [00:03<00:00, 257.45it/s]
```
Imaging the case you have a few dataset files, each with millions of frames, then you print (multiple) millions of rows for nothing. Such print will affect negatively performance.
Such information is not necessary, so I suggest to remove it

How to you thing?

**Comment by YutackPark** [comment]
I couldn't understand why your system prints tqdm with newlines, but I'm happy improve code to have option to turn it off.

Before than, I suggest to try selectively redirect such outputs into temporary directory (such as `/tmp`) or null (`/dev/null`), as tqdm prints it to `stderr`, not `stdout`. For example,
`sevenn_graph_build some_data 4.0 2> /dev/null`
will prints nothing to your screen.

**Comment by thangckt** [comment]
hi @YutackPark 

>as tqdm prints it to `stderr`

This is why I suggest to disable it. 
When working with campus clusters, one normally submit their jobs and spend long wait time in queue.
Then, nervously wait for their jobs exec and looking for `stderr` file if it outputs anything. 
It will not happy if  there is a non-zero size `stderr` file.  Some errors should be catched, but should not irrelevant tqdm print.

Thanks.

**Comment by thangckt** [comment]
this issue is not so serious, so I will close it to focus on more important issues
