### ISSUE TITLE
error in deploy script

### ISSUE THREAD

**Issue by thangckt** [MDIL-SNU/SevenNet#132]
Dear Devs, 

deploy script in main branch
```
sevenn_get_model checkpoint_best.pth
```
get this error
```
\site-packages\sevenn\scripts\deploy.py", line 27, in deploy
    model.prepand_module('edge_preprocess', EdgePreprocess(True))
\Lib\site-packages\sevenn\nn\sequential.py", line 83, in prepand_module
    self._modules.move_to_end(key, last=False)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'move_to_end'
```

**Comment by YutackPark** [comment]
Could you share more details? I might need the `torch_geometric` version and minimal `input.yaml` to reproduce the error.

Minimal tests are already included in below for 7net-0 model and I have also checked `example_inputs/training`
https://github.com/MDIL-SNU/SevenNet/blob/125c9cfae50be4a34d37766f6d55e5e51ace16cb/tests/unit_tests/test_cli.py#L45

**Comment by thangckt** [comment]
hi @YutackPark 

I did not read the docs careful for requirement of torch version.
The problem is due to torch version.

Sorry for bothering.

**Comment by YutackPark** [comment]
Ah, the torch version added recently. Newer torch version doesn't work well with torch script (deploy). I think they changed something. I'll open issue regarding torch version.
