### ISSUE TITLE
Error in importing OUTCAR without stress data

### ISSUE THREAD

**Issue by petitcloud** [MDIL-SNU/SEVENNet#3]
안녕하세요, KIST 계산과학연구센터 이병주라고 합니다.
simplenn을 포함해서, 좋은 프로그램 개발해 주셔서 잘 쓰고 있습니다.
다름이 아니라 AIMD 데이터와 같이 stress 데이터 자체가 OUTCAR에 기록되어 있지 않은 경우, 
input.yaml에서 is_train_stress 를 False로 지정하더라도, 파일을 읽을 때 기본적으로 stress를 읽도록 되어 있어 property not found 에러가 나네요.
이 부분을 제가 임의로 예외처리 하고 코드를 돌려보면 잘 도는 것 같습니다.
코드 업데이트 때 참고하시면 좋을 것 같습니다~~
감사합니다.
이병주 드림.

**Comment by YutackPark** [comment]
안녕하세요, 서울대학교 전산재료연구실 박유택입니다.
불편을 드려 죄송합니다. 말씀해주신 부분은 저도 dev branch에선 수정되었습니다. 향후 테스트 후 main에 업데이트 될 예정입니다. 리포트 감사합니다!

박유택 올림.

**Comment by YutackPark** [comment]
The dev branch is merged into main.
