### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by janosh** [MDIL-SNU/SevenNet#52]
opening this to keep track of the PyPI release for SevenNet [mentioned here](https://github.com/janosh/matbench-discovery/pull/112#issuecomment-2227561842)

**Comment by YutackPark** [comment]
Thank you for your patience. SevenNet is now released on PyPI. I have replaced `torch_scatter`, which required manual installation steps, with pure PyTorch functions. With PyTorch installed, SevenNet can now be installed via pip.

You may be interested in pre-trained models. Our model, which is around 10 MB, is included in the project itself as a data file. It can be loaded, for example, as an ASE calculator:
```python
from sevenn.sevennet_calculator import SevenNetCalculator
sevenet_0_cal = SevenNetCalculator("7net-0_11July2024", device='cpu')
```

Let me know if you need any further suggestions!
