### ISSUE TITLE
speed up inference just by torch 

### ISSUE THREAD

**Issue by heyfavour** [MDIL-SNU/SevenNet#55]
can speed  up inference just in pytorch without lammps? i have my model , and i just want to speed up it in python , i want to split gnn message in multi-gpu,but i can't get grad

**Comment by YutackPark** [comment]
Sorry, but it is not feasible. You may try using LAMMPS with the Python interface.

If we try the same approach as I implemented for LAMMPS with the multi-GPU version of SevenNet, we would have to implement the fundamentals of the parallel algorithm in LAMMPS to Python, which is non-trivial.
