### ISSUE TITLE
Get nan values during train

### ISSUE THREAD

**Issue by thangckt** [MDIL-SNU/SevenNet#90]
Dear,

I try to train a simple model. and get all values in loss
The logfile as attachment.

Can you have a little guide.
Thank you so much

[log.log](https://github.com/user-attachments/files/16988614/log.log)

**Comment by thangckt** [comment]
hi @YutackPark 
I set it `False`

Then train now interrupt without any error, at log
```
Trainer initialized, ready to training
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
Epoch 1/10  lr: 0.001000
------------------------------------------------------------------------------------------------------------------------
```
Do you know why?

**Comment by YutackPark** [comment]
Firstly, you should uncomment "# - ['TotalLoss', 'None']". SevenNet needs total loss to determine the best checkpoint to save.
However, SevenNet should raise an error and quit if this is the case.

I failed to reproduce the issue with the same input but a different training set. Maybe, it is just that training is very slow. Could you share your dataset if you don't mind?

**Comment by thangckt** [comment]
hi @YutackPark 

The dataset at [this link](https://github.com/BingqingCheng/ab-initio-thermodynamics-of-water/blob/master/training-set/dataset_1593.xyz)

With PR#89, you can set input as
```
data_format: 'ase' 
data_format_args:                         
        energy_key: 'TotEnergy'                 
        force_key: 'force' 
```
Then you can repoduce the problem.
I confirn that, above problem occur on Windows, when I test on Linux the problem disappear, and code can run well
