### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by janosh** [MDIL-SNU/SevenNet#96]
version [0.9.3](https://pypi.org/project/sevenn/0.9.3) was yanked due to a bug in `e3gnn_parallel` a few days ago. since that was the only pypi release for the `sevenn` package, downstream CIs are now failing. could we get a new release?

**Comment by YutackPark** [comment]
Just uploaded v0.9.3.post1. Exactly the same as before but fixed `e3gnn_parallel` and fixed version names (can be accessed as sevenn.__version__)

Reference tag: https://github.com/MDIL-SNU/SevenNet/releases/tag/v0.9.3.post1

**Comment by janosh** [comment]
@YutackPark thanks for the quick fix! 👍
