### ISSUE TITLE
Pass the pre-loaded model when initialising the calculator, rather than loading the model inside the calculator.

### ISSUE THREAD

**Issue by dembart** [MDIL-SNU/SevenNet#99]
Hello, 

What do you thing about passing the instance of the pre-loaded model as an argument when initialising the calculator, rather than loading the model (from the specified path) inside the calculator ? If you need multiple calculators, it should be faster to load a model and share it between the calculators than to load the model multiple times for each calculator.

**Comment by YutackPark** [comment]
I agree with you. I'll add this to my TODO list (#86).
